# Generated by Django 3.0.7 on 2020-06-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='spo2',
            new_name='spo2_evening',
        ),
        migrations.AddField(
            model_name='daily',
            name='spo2_morning',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Relative', 'Relative')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='close_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='hospitalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name_of_hospital',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_patient',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.CharField(blank=True, choices=[('Roha', 'Roha'), ('Mahad', 'Mahad'), ('Pune', 'Pune')], max_length=100),
        ),
        migrations.AlterField(
            model_name='daily',
            name='temperature_evening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='temperature_morning',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
