# Generated by Django 3.0.7 on 2020-06-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='report',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hr_comment',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CloseContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('relation', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users_module.Patient')),
            ],
        ),
    ]
