# Generated by Django 3.0.7 on 2020-06-27 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0002_auto_20200627_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dry_cough', models.BooleanField(default=False)),
                ('dry_cough_frequency', models.IntegerField()),
                ('sore_throat', models.BooleanField(default=False)),
                ('body_ache', models.BooleanField(default=False)),
                ('body_ache_intensity', models.IntegerField()),
                ('head_ache', models.BooleanField(default=False)),
                ('head_ache_intensity', models.IntegerField()),
                ('weakness', models.BooleanField(default=False)),
                ('anosmia', models.BooleanField(default=False)),
                ('ageusia', models.BooleanField(default=False)),
                ('diarrhoea', models.BooleanField(default=False)),
                ('diarrhoea_frequency', models.IntegerField()),
                ('temperature_morning', models.IntegerField()),
                ('temperature_evening', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('appetite_level', models.IntegerField()),
                ('abnormal_medical_reports', models.BooleanField(default=False)),
                ('report', models.URLField()),
                ('difficulty_breathing', models.BooleanField(default=False)),
                ('covid_test', models.BooleanField(default=False)),
                ('covid_test_outcome', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
