# Generated by Django 3.0.7 on 2020-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0003_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='appetite_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='body_ache_intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='diarrhoea_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='dry_cough_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='head_ache_intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='report',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='spo2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='temperature_evening',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='temperature_morning',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
