# Generated by Django 3.0.7 on 2020-06-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0004_auto_20200627_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='on_immunosuppressents',
            new_name='on_immuno_suppressants',
        ),
    ]
