# Generated by Django 3.0.7 on 2020-06-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0006_auto_20200628_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_done',
            field=models.BooleanField(default=False),
        ),
    ]
