# Generated by Django 3.0.7 on 2020-06-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_module', '0007_user_test_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='covid_test',
            new_name='report_received',
        ),
    ]
